spring:
  datasource:
    url: jdbc:postgresql://10.0.147.41:5432/db
    username: postgres
    password: postgres

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.0.147.41:8090/realms/ctrlf

keycloak:
  admin:
    base-url: http://10.0.147.41:8090
    realm: ctrlf
    client-id: infra-admin
    client-secret: changeme

app:
  rag:
    ai:
      base-url: http://192.168.0.112:8000
      token: changeme
      timeout-seconds: 10