apiVersion: v1
kind: Service
metadata:
  name: education-service
  namespace: default
spec:
  selector:
    app: education-service
  ports:
    - protocol: TCP
      port: 9002      # 외부/내부에서 접속할 포트
      targetPort: 8080 # 컨테이너 내부 포트
  type: ClusterIP
